spring:
  application:
    name: service-a

  config:
    import:     # it recognizes .env files
      - optional:file:service-a/.env[.properties]
      - optional:file:.env[.properties]

  security:
    jwt:
      secret: ${JWT_SECRET}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres

service-b: ${SERVICE_B}
header_secret: ${INTERNAL_TOKEN}

logging:
  level:
    com.acheron.servicea: debug